# List of all 18 patterns and their 30 cards data.
# This file serves as the database for generating 540 cards programmatically.

DATA = {
    1: [ # 3-Consonant Cluster Elision
        ("last night", "las night", "I went to sleep late {{c1::last night}}.", "anoche"),
        ("next door", "nex door", "He lives {{c1::next door}} to me.", "al lado"),
        ("must be", "mus be", "That {{c1::must be}} the answer.", "debe ser"),
        ("just one", "jus one", "I only want {{c1::just one}} piece.", "solo uno"),
        ("best friend", "bes friend", "She is my {{c1::best friend}}.", "mejor amigo"),
        ("cold drink", "col drink", "Would you like a {{c1::cold drink}}?", "bebida fría"),
        ("old man", "ol man", "The {{c1::old man}} walked slowly.", "hombre viejo"),
        ("first time", "firs time", "This is the {{c1::first time}} I've been here.", "primera vez"),
        ("last time", "las time", "That was the {{c1::last time}} I saw him.", "última vez"),
        ("next time", "nex time", "We'll do better {{c1::next time}}.", "próxima vez"),
        ("left side", "lef side", "Turn on the {{c1::left side}} of the street.", "lado izquierdo"),
        ("right now", "righ now", "I need you to do it {{c1::right now}}.", "ahora mismo"),
        ("just now", "jus now", "He left the office {{c1::just now}}.", "hace un momento"),
        ("soft drink", "sof drink", "Do you want a {{c1::soft drink}} or water?", "refresco"),
        ("hand bag", "han bag", "She carried a small {{c1::hand bag}}.", "bolso de mano"),
        ("sand castle", "san castle", "They built a {{c1::sand castle}} on the beach.", "castillo de arena"),
        ("blind man", "blin man", "The {{c1::blind man}} had a guide dog.", "hombre ciego"),
        ("wind storm", "win storm", "There was a heavy {{c1::wind storm}} last night.", "tormenta de viento"),
        ("kind word", "kin word", "A {{c1::kind word}} makes a big difference.", "palabra amable"),
        ("grand standing", "gran standing", "Stop {{c1::grand standing}} in front of everyone.", "presumir"),
        ("wild card", "wil card", "They entered as a {{c1::wild card}} team.", "comodín"),
        ("bold move", "bol move", "That was a {{c1::bold move}} by the CEO.", "movimiento audaz"),
        ("gold mine", "gol mine", "This business is a real {{c1::gold mine}}.", "mina de oro"),
        ("cold cuts", "col cuts", "We had {{c1::cold cuts}} for lunch.", "embutidos"),
        ("fast food", "fas food", "I try not to eat too much {{c1::fast food}}.", "comida rápida"),
        ("most people", "mos people", "{{c1::Most people}} agree with this decision.", "la mayoría de la gente"),
        ("post office", "pos office", "Where is the nearest {{c1::post office}}?", "oficina de correos"),
        ("west coast", "wes coast", "They moved to the {{c1::west coast}} last year.", "costa oeste"),
        ("east coast", "eas coast", "I prefer the weather on the {{c1::east coast}}.", "costa este"),
        ("worst case", "wors case", "In the {{c1::worst case}} scenario, we rollback.", "peor de los casos")
    ],
    2: [ # Flap T / Intervocalic Flapping
        ("water", "wa-der", "She drinks a lot of {{c1::water}} every day.", "agua"),
        ("better", "be-der", "This coffee is getting {{c1::better}}.", "mejor"),
        ("butter", "bu-der", "Pass the {{c1::butter}}, please.", "mantequilla"),
        ("city", "ci-dy", "New York is a huge {{c1::city}}.", "ciudad"),
        ("pretty", "pri-dy", "She is a {{c1::pretty}} smart girl.", "bastante / linda"),
        ("getting", "ge-ding", "It's {{c1::getting}} late.", "haciéndose / poniéndose"),
        ("putting", "pu-ding", "Stop {{c1::putting}} it off.", "poner"),
        ("hitting", "hi-ding", "He kept {{c1::hitting}} the wall.", "golpear"),
        ("sitting", "si-ding", "She was {{c1::sitting}} by the window.", "sentada"),
        ("dirty", "dir-dy", "His shoes were {{c1::dirty}}.", "sucio"),
        ("party", "par-dy", "Are you going to the {{c1::party}}?", "fiesta"),
        ("thirty", "thir-dy", "He is {{c1::thirty}} years old.", "treinta"),
        ("forty", "for-dy", "The price is {{c1::forty}} dollars.", "cuarenta"),
        ("seventy", "seven-dy", "My grandfather is {{c1::seventy}}.", "setenta"),
        ("beauty", "beau-dy", "She is a natural {{c1::beauty}}.", "belleza"),
        ("duty", "du-dy", "It's my {{c1::duty}} to tell you.", "deber"),
        ("cut it", "cu-dit", "Can you {{c1::cut it}} out?", "cortarlo / parar"),
        ("get it", "ge-dit", "I don't {{c1::get it}}.", "entenderlo"),
        ("let it", "le-dit", "Just {{c1::let it}} go.", "dejarlo"),
        ("set it", "se-dit", "Please {{c1::set it}} up.", "configurarlo"),
        ("put it", "pu-dit", "Where should I {{c1::put it}}?", "ponerlo"),
        ("write it", "wri-dit", "Could you {{c1::write it}} down?", "escribirlo"),
        ("read it", "rea-dit", "Did you {{c1::read it}} yet?", "leerlo"),
        ("forgot it", "forgo-dit", "I completely {{c1::forgot it}}.", "olvidarlo"),
        ("shut it", "shu-dit", "Please {{c1::shut it}} down.", "cerrarlo"),
        ("wait a", "wai-da", "Can you {{c1::wait a}} minute?", "esperar un"),
        ("meet a", "mee-da", "I want to {{c1::meet a}} new friend.", "conocer a un"),
        ("great idea", "grea-didea", "That's a {{c1::great idea}}.", "gran idea"),
        ("not at all", "no-da-tall", "No, {{c1::not at all}}.", "para nada"),
        ("what a", "wha-da", "{{c1::What a}} beautiful day!", "qué un")
    ],
    3: [ # Glottal Stop
        ("button", "bu'n", "Press the red {{c1::button}}.", "botón"),
        ("important", "impor'nt", "This is very {{c1::important}}.", "importante"),
        ("certain", "cer'n", "Are you {{c1::certain}} about this?", "seguro"),
        ("mountain", "moun'n", "We climbed the {{c1::mountain}}.", "montaña"),
        ("written", "wri'n", "It was {{c1::written}} in the contract.", "escrito"),
        ("bitten", "bi'n", "He was {{c1::bitten}} by a dog.", "mordido"),
        ("beaten", "bea'n", "They were {{c1::beaten}} in the game.", "derrotado"),
        ("eaten", "ea'n", "Have you {{c1::eaten}} yet?", "comido"),
        ("kitten", "ki'n", "The {{c1::kitten}} was sleeping.", "gatito"),
        ("mitten", "mi'n", "I lost my left {{c1::mitten}}.", "mitón / guante"),
        ("cotton", "co'n", "This shirt is made of {{c1::cotton}}.", "algodón"),
        ("forgotten", "forgo'n", "I have completely {{c1::forgotten}}.", "olvidado"),
        ("rotten", "ro'n", "The apple was {{c1::rotten}}.", "podrido"),
        ("curtain", "cur'n", "Close the {{c1::curtain}}, please.", "cortina"),
        ("Latin", "La'n", "They study {{c1::Latin}} at school.", "latín"),
        ("satin", "sa'n", "She wore a {{c1::satin}} dress.", "raso / satén"),
        ("frighten", "frigh'n", "Don't {{c1::frighten}} the birds.", "asustar"),
        ("tighten", "tigh'n", "You need to {{c1::tighten}} the screw.", "apretar"),
        ("flatten", "fla'n", "We need to {{c1::flatten}} the box.", "aplanar"),
        ("sweeten", "swee'n", "Add sugar to {{c1::sweeten}} it.", "endulzar"),
        ("threaten", "threa'n", "Don't {{c1::threaten}} me.", "amenazar"),
        ("shorten", "shor'n", "Can we {{c1::shorten}} the meeting?", "acortar"),
        ("soften", "sof'n", "Use lotion to {{c1::soften}} your skin.", "suavizar"),
        ("Manhattan", "Manha'n", "He lives in {{c1::Manhattan}}.", "Manhattan"),
        ("brighten", "brigh'n", "Sunlight will {{c1::brighten}} the room.", "iluminar"),
        ("broaden", "broa'n", "Travel will {{c1::broaden}} your mind.", "ampliar"),
        ("dampen", "dam'n", "Don't let it {{c1::dampen}} your spirits.", "desanimar"),
        ("gladden", "glad'n", "It will {{c1::gladden}} her heart.", "alegrar"),
        ("heighten", "heigh'n", "This will {{c1::heighten}} the tension.", "aumentar"),
        ("loosen", "loo's'n", "Can you {{c1::loosen}} the knot?", "aflojar")
    ],
    4: [ # Nasal T-Deletion
        ("internet", "innernet", "I checked the {{c1::internet}}.", "internet"),
        ("twenty", "tweny", "He has {{c1::twenty}} dollars.", "veinte"),
        ("center", "cener", "They met in the {{c1::center}} of the park.", "centro"),
        ("international", "innernational", "It was an {{c1::international}} event.", "internacional"),
        ("interview", "innerview", "I have a job {{c1::interview}} tomorrow.", "entrevista"),
        ("winter", "winner", "The weather is cold in the {{c1::winter}}.", "invierno"),
        ("enter", "enner", "Please {{c1::enter}} your code.", "ingresar"),
        ("printer", "prinner", "The {{c1::printer}} is out of paper.", "impresora"),
        ("painter", "painer", "He is a famous {{c1::painter}}.", "pintor"),
        ("counter", "couner", "Leave it on the {{c1::counter}}.", "mostrador"),
        ("hunter", "hunner", "The {{c1::hunter}} walked in the woods.", "cazador"),
        ("mental", "mennal", "It takes a lot of {{c1::mental}} energy.", "mental"),
        ("rental", "rennal", "We signed the {{c1::rental}} agreement.", "alquiler"),
        ("dental", "dennal", "I need to make a {{c1::dental}} appointment.", "dental"),
        ("gentle", "gennel", "Be {{c1::gentle}} with the baby.", "amable / suave"),
        ("plenty", "pleny", "We have {{c1::plenty}} of time.", "de sobra / mucho"),
        ("interstate", "innerstate", "Take the {{c1::interstate}} highway.", "interestatal"),
        ("interactive", "inneractive", "This is an {{c1::interactive}} game.", "interactivo"),
        ("interaction", "inneraction", "Social {{c1::interaction}} is important.", "interacción"),
        ("interrupted", "innerrupted", "He was {{c1::interrupted}} mid-speech.", "interrumpido"),
        ("interest", "innerest", "He showed a lot of {{c1::interest}}.", "interés"),
        ("interesting", "inneresting", "That is an {{c1::interesting}} story.", "interesante"),
        ("interference", "innerference", "There is static {{c1::interference}}.", "interferencia"),
        ("integration", "innergration", "System {{c1::integration}} is complete.", "integración"),
        ("interpreter", "innerpreter", "They hired an {{c1::interpreter}}.", "intérprete"),
        ("intensity", "innensity", "The storm increased in {{c1::intensity}}.", "intensidad"),
        ("continental", "conninental", "We had a {{c1::continental}} breakfast.", "continental"),
        ("disadvantage", "disadvanage", "That is a big {{c1::disadvantage}}.", "desventaja"),
        ("advantage", "advanage", "Take {{c1::advantage}} of the offer.", "ventaja"),
        ("percentage", "percenage", "What is the {{c1::percentage}} of growth?", "porcentaje")
    ],
    5: [ # Yod Coalescence
        ("don't you", "don-choo", "{{c1::Don't you}} want to come?", "no quieres"),
        ("would you", "wood-joo", "{{c1::Would you}} help me?", "podrías"),
        ("miss you", "mi-shoo", "I really {{c1::miss you}}.", "te extraño"),
        ("as you know", "a-zhoo know", "{{c1::As you know}}, we are late.", "como sabes"),
        ("could you", "cood-joo", "{{c1::Could you}} repeat that?", "podrías"),
        ("did you", "did-joo", "{{c1::Did you}} see it?", "lo viste"),
        ("won't you", "won-choo", "{{c1::Won't you}} sit down?", "no te sentarás"),
        ("can't you", "can-choo", "{{c1::Can't you}} do it?", "no puedes"),
        ("meet you", "mee-choo", "Nice to {{c1::meet you}}.", "conocerte"),
        ("hit you", "hi-choo", "Did it {{c1::hit you}}?", "te golpeó"),
        ("had you", "had-joo", "If {{c1::had you}} known, would you go?", "si hubieras"),
        ("need you", "nee-joo", "I {{c1::need you}} here.", "te necesito"),
        ("bless you", "ble-shoo", "{{c1::Bless you}}! Did you sneeze?", "salud / dios te bendiga"),
        ("this year", "thi-sheer", "We are busy {{c1::this year}}.", "este año"),
        ("last year", "las-cheer", "It happened {{c1::last year}}.", "el año pasado"),
        ("not yet", "no-chet", "I'm {{c1::not yet}} ready.", "aún no"),
        ("did you ever", "jev-er", "{{c1::Did you ever}} try this?", "alguna vez has"),
        ("what you need", "wha-choo need", "This is {{c1::what you need}}.", "lo que necesitas"),
        ("about you", "abou-choo", "What {{c1::about you}}?", "qué hay de ti"),
        ("want you to", "wan-choo-tuh", "I {{c1::want you to}} go.", "quiero que vayas"),
        ("got you", "got-choo", "I {{c1::got you}} a gift.", "te conseguí / te entendí"),
        ("told you", "tol-joo", "I {{c1::told you}} so.", "te lo dije"),
        ("behind you", "behin-joo", "It's right {{c1::behind you}}.", "detrás de ti"),
        ("find you", "fin-joo", "I will {{c1::find you}}.", "te encontraré"),
        ("mind you", "min-joo", "It's hard, {{c1::mind you}}.", "ten en cuenta"),
        ("trust you", "trus-choo", "I {{c1::trust you}}.", "confío en ti"),
        ("suggest you", "sugges-choo", "I {{c1::suggest you}} wait.", "te sugiero que"),
        ("lost you", "los-choo", "I think I {{c1::lost you}}.", "te perdí"),
        ("please you", "plea-zhoo", "It's hard to {{c1::please you}}.", "complacerte"),
        ("phrase you used", "phra-zhoo used", "That {{c1::phrase you used}} was nice.", "frase que usaste")
    ],
    6: [ # Resyllabification
        ("check it out", "che-ki-tout", "Hey, {{c1::check it out}}!", "míralo"),
        ("hold on", "hol-don", "Can you {{c1::hold on}}?", "espera"),
        ("an apple", "a-napple", "She ate {{c1::an apple}}.", "una manzana"),
        ("far away", "fa-ra-way", "It's {{c1::far away}}.", "muy lejos"),
        ("pick it up", "pi-ki-tup", "Please {{c1::pick it up}}.", "recógelo"),
        ("take it easy", "tay-ki-tee-zy", "Just {{c1::take it easy}}.", "tómalo con calma"),
        ("give it up", "gi-vi-tup", "Don't {{c1::give it up}}.", "te rindas"),
        ("work it out", "wor-ki-tout", "We can {{c1::work it out}}.", "resolverlo"),
        ("turn it on", "tur-ni-ton", "Can you {{c1::turn it on}}?", "encenderlo"),
        ("come on in", "co-mo-nin", "Please {{c1::come on in}}.", "pasa adentro"),
        ("get in", "ge-tin", "Let's {{c1::get in}} the car.", "entrar"),
        ("put it away", "pu-ti-taway", "Please {{c1::put it away}}.", "guárdalo"),
        ("set it off", "se-ti-toff", "That will {{c1::set it off}}.", "desactivarlo/activarlo"),
        ("wrap it up", "wra-pi-tup", "Let's {{c1::wrap it up}}.", "terminar"),
        ("run away", "ru-na-way", "Don't {{c1::run away}}.", "escapar"),
        ("look at", "loo-kat", "Take a {{c1::look at}} this.", "mirar a"),
        ("find out", "fin-dout", "We need to {{c1::find out}}.", "enterarse"),
        ("stand up", "stan-dup", "Please {{c1::stand up}}.", "ponerse de pie"),
        ("think of", "thin-kov", "What do you {{c1::think of}} this?", "pensar de"),
        ("read it", "rea-dit", "Can you {{c1::read it}}?", "leerlo"),
        ("write about", "wri-ta-bout", "What did you {{c1::write about}}?", "escribir sobre"),
        ("clean up", "clea-nup", "We must {{c1::clean up}}.", "limpiar"),
        ("drink it", "drin-kit", "Go ahead and {{c1::drink it}}.", "bébelo"),
        ("wake up", "wa-kup", "Time to {{c1::wake up}}.", "despertar"),
        ("shake it", "sha-kit", "Make sure you {{c1::shake it}}.", "sacudirlo"),
        ("speak out", "spea-kout", "Don't be afraid to {{c1::speak out}}.", "hablar abiertamente"),
        ("walk away", "wal-ka-way", "Just {{c1::walk away}}.", "alejarse"),
        ("laugh at", "lau-fhat", "Don't {{c1::laugh at}} him.", "reírse de"),
        ("cough up", "cou-fhp", "He had to {{c1::cough up}} the money.", "soltar (pagar)"),
        ("keep on", "kee-pon", "Just {{c1::keep on}} trying.", "continuar")
    ],
    7: [ # Weak H-Dropping
        ("tell him", "tell-im", "Did you {{c1::tell him}}?", "decirle a él"),
        ("ask her", "as-ker", "Go and {{c1::ask her}}.", "pregúntale a ella"),
        ("what did he say", "wha-di-dee say", "{{c1::What did he say}}?", "qué dijo él"),
        ("should have", "should-av", "I {{c1::should have}} known.", "debería haber"),
        ("would have", "would-av", "It {{c1::would have}} been nice.", "habría sido"),
        ("could have", "could-av", "We {{c1::could have}} won.", "podríamos haber"),
        ("give him", "give-im", "Please {{c1::give him}} a call.", "dale"),
        ("saw her", "saw-er", "I {{c1::saw her}} yesterday.", "la vi"),
        ("tell her", "tell-er", "Don't {{c1::tell her}}.", "dile a ella"),
        ("ask him", "as-kim", "Did you {{c1::ask him}} yet?", "pregúntale a él"),
        ("call her", "call-er", "Can you {{c1::call her}}?", "llamarla"),
        ("call him", "call-im", "I'll {{c1::call him}} later.", "lo llamaré"),
        ("find her", "find-er", "We need to {{c1::find her}}.", "encontrarla"),
        ("find him", "find-im", "Did you {{c1::find him}}?", "lo encontraste"),
        ("help her", "help-er", "Go {{c1::help her}}.", "ayúdala"),
        ("help him", "help-im", "We must {{c1::help him}}.", "ayudarlo"),
        ("love her", "love-er", "I {{c1::love her}}.", "la amo"),
        ("love him", "love-im", "They {{c1::love him}}.", "lo aman"),
        ("trust her", "trust-er", "I {{c1::trust her}}.", "confío en ella"),
        ("trust him", "trust-im", "Do you {{c1::trust him}}?", "confías en él"),
        ("leave her", "leave-er", "Don't {{c1::leave her}} behind.", "la dejes"),
        ("leave him", "leave-im", "We should {{c1::leave him}} alone.", "dejarlo"),
        ("know her", "know-er", "I don't {{c1::know her}}.", "la conozco"),
        ("know him", "know-im", "Do you {{c1::know him}}?", "lo conoces"),
        ("for her", "for-er", "This gift is {{c1::for her}}.", "para ella"),
        ("for him", "for-im", "I bought this {{c1::for him}}.", "para él"),
        ("behind her", "behind-er", "He was {{c1::behind her}}.", "detrás de ella"),
        ("behind him", "behind-im", "She stood {{c1::behind him}}.", "detrás de él"),
        ("with her", "with-er", "Are you going {{c1::with her}}?", "con ella"),
        ("with him", "with-im", "I went {{c1::with him}}.", "con él")
    ],
    8: [ # Schwa Reduction
        ("fish and chips", "fish 'n chips", "I ordered {{c1::fish and chips}}.", "pescado con patatas"),
        ("go to the store", "go tuh thuh store", "I need to {{c1::go to the store}}.", "ir a la tienda"),
        ("can go", "kn go", "I {{c1::can go}} tomorrow.", "puedo ir"),
        ("piece of cake", "piece av cake", "It was a {{c1::piece of cake}}.", "pan comido"),
        ("for you", "fer yuh", "This is {{c1::for you}}.", "para ti"),
        ("more than that", "more thn that", "I want {{c1::more than that}}.", "más que eso"),
        ("as fast as", "az fast az", "Run {{c1::as fast as}} you can.", "tan rápido como"),
        ("some of them", "some av thm", "I want {{c1::some of them}}.", "algunos de ellos"),
        ("was good", "wz good", "The movie {{c1::was good}}.", "estuvo buena"),
        ("but I", "bt I", "I tried {{c1::but I}} failed.", "pero yo"),
        ("from here", "frm here", "It's far {{c1::from here}}.", "desde aquí"),
        ("have done", "hv done", "I {{c1::have done}} it.", "he hecho"),
        ("does he", "dz he", "Where {{c1::does he}} live?", "vive él"),
        ("at school", "t school", "He is {{c1::at school}}.", "en la escuela"),
        ("to eat", "t'eat", "Something {{c1::to eat}}.", "para comer"),
        ("you and me", "you 'n me", "Just {{c1::you and me}}.", "tú y yo"),
        ("bread and butter", "bread 'n butter", "This is my {{c1::bread and butter}}.", "sustento / pan con mantequilla"),
        ("rock and roll", "rock 'n roll", "I love {{c1::rock and roll}}.", "rock and roll"),
        ("day and night", "day 'n night", "We worked {{c1::day and night}}.", "día y noche"),
        ("black and white", "black 'n white", "It's a {{c1::black and white}} photo.", "blanco y negro"),
        ("time after time", "timeaftertime", "It happens {{c1::time after time}}.", "una y otra vez"),
        ("out of order", "out av order", "The machine is {{c1::out of order}}.", "fuera de servicio"),
        ("cup of tea", "cup av tea", "Would you like a {{c1::cup of tea}}?", "taza de té"),
        ("glass of water", "glass av water", "Can I get a {{c1::glass of water}}?", "vaso de agua"),
        ("bottle of wine", "bottle av wine", "We bought a {{c1::bottle of wine}}.", "botella de vino"),
        ("slice of pizza", "slice av pizza", "I want a {{c1::slice of pizza}}.", "porción de pizza"),
        ("lot of money", "lot av money", "That costs a {{c1::lot of money}}.", "mucho dinero"),
        ("end of the road", "end av thuh road", "We reached the {{c1::end of the road}}.", "final del camino"),
        ("middle of the night", "middle av thuh night", "He woke up in the {{c1::middle of the night}}.", "mitad de la noche"),
        ("top of the world", "top av thuh world", "I feel on {{c1::top of the world}}.", "cima del mundo")
    ],
    9: [ # Linking R & Intrusive R
        ("law and order", "law-r-an-order", "I watch {{c1::law and order}}.", "ley y orden"),
        ("idea of it", "idea-r-of-it", "I like the {{c1::idea of it}}.", "la idea de eso"),
        ("far away", "far-away", "The house is {{c1::far away}}.", "muy lejos"),
        ("four of them", "four-of-them", "We need {{c1::four of them}}.", "cuatro de ellos"),
        ("media event", "media-r-event", "This is a big {{c1::media event}}.", "evento mediático"),
        ("sofa and chair", "sofa-r-and-chair", "We bought a {{c1::sofa and chair}}.", "sofá y silla"),
        ("drama alert", "drama-r-alert", "There is a new {{c1::drama alert}}.", "alerta de drama"),
        ("formula one", "formula-r-one", "He drives in {{c1::formula one}}.", "fórmula uno"),
        ("tuna salad", "tuna-r-salad", "I had a {{c1::tuna salad}}.", "ensalada de atún"),
        ("vanilla ice", "vanilla-r-ice", "I prefer {{c1::vanilla ice}} cream.", "helado de vainilla"),
        ("banana split", "banana-r-split", "Let's share a {{c1::banana split}}.", "banana split"),
        ("area of", "area-r-of", "This is an {{c1::area of}} concern.", "área de"),
        ("data analysis", "data-r-analysis", "We did some {{c1::data analysis}}.", "análisis de datos"),
        ("camera angle", "camera-r-angle", "Adjust the {{c1::camera angle}}.", "ángulo de cámara"),
        ("pizza oven", "pizza-r-oven", "We built a {{c1::pizza oven}}.", "horno de pizza"),
        ("soda and", "soda-r-and", "Give me a {{c1::soda and}} lime.", "soda y"),
        ("extra information", "extra-r-information", "Do you need {{c1::extra information}}?", "información extra"),
        ("major issue", "major-r-issue", "This is a {{c1::major issue}}.", "problema mayor"),
        ("clear air", "clear-r-air", "We enjoyed the {{c1::clear air}}.", "aire limpio"),
        ("poor old", "poor-r-old", "The {{c1::poor old}} dog was lost.", "pobre viejo"),
        ("door open", "door-r-open", "Leave the {{c1::door open}}.", "puerta abierta"),
        ("floor area", "floor-r-area", "The {{c1::floor area}} is huge.", "área del suelo"),
        ("car engine", "car-r-engine", "The {{c1::car engine}} is loud.", "motor de coche"),
        ("bar owner", "bar-r-owner", "He is the {{c1::bar owner}}.", "dueño del bar"),
        ("star actor", "star-r-actor", "She is a {{c1::star actor}}.", "actor estrella"),
        ("for instance", "for-r-instance", "Take this, {{c1::for instance}}.", "por ejemplo"),
        ("more options", "more-r-options", "We need {{c1::more options}}.", "más opciones"),
        ("here and there", "here-r-and-there", "We searched {{c1::here and there}}.", "aquí y allá"),
        ("there is", "there-r-is", "Is {{c1::there is}} any problem?", "hay"),
        ("where are you", "where-r-are-you", "{{c1::Where are you}} going?", "dónde estás")
    ],
    10: [ # Lexical Chunks
        ("going to", "gonna", "I'm {{c1::going to}} leave.", "voy a"),
        ("want to", "wanna", "I {{c1::want to}} go.", "quiero"),
        ("got to", "gotta", "I've {{c1::got to}} run.", "tengo que"),
        ("have to", "hafta", "We {{c1::have to}} try.", "tenemos que"),
        ("ought to", "oughta", "You {{c1::ought to}} see it.", "deberías"),
        ("kind of", "kinda", "It's {{c1::kind of}} cold.", "más o menos / un poco"),
        ("sort of", "sorta", "I {{c1::sort of}} like it.", "en cierta manera / algo"),
        ("out of", "outta", "Get {{c1::out of}} here.", "fuera de"),
        ("let me", "lemme", "{{c1::Let me}} see.", "déjame"),
        ("give me", "gimme", "{{c1::Give me}} a break.", "dame"),
        ("come on", "c'mon", "{{c1::Come on}}, let's go.", "vamos"),
        ("should have", "shoulda", "You {{c1::should have}} called.", "deberías haber"),
        ("would have", "woulda", "I {{c1::would have}} come.", "habría"),
        ("could have", "coulda", "We {{c1::could have}} helped.", "podríamos haber"),
        ("must have", "musta", "He {{c1::must have}} left.", "debe haber"),
        ("don't know", "dunno", "I {{c1::don't know}}.", "no sé"),
        ("what are you", "whatcha", "{{c1::What are you}} doing?", "qué estás"),
        ("supposed to", "s'posed to", "We are {{c1::supposed to}} start.", "se supone que debemos"),
        ("used to", "used to", "I {{c1::used to}} swim.", "solía"),
        ("has to", "hasta", "She {{c1::has to}} work.", "tiene que"),
        ("got you", "gotcha", "I {{c1::got you}}.", "te entendí / te pillé"),
        ("am going to", "imma", "I {{c1::am going to}} do it.", "voy a (jerga muy informal)"),
        ("how did you", "howdy", "{{c1::How did you}} do that?", "cómo lo hiciste"),
        ("bet you", "betcha", "I {{c1::bet you}} can't.", "te apuesto que"),
        ("don't you", "dontcha", "{{c1::Don't you}} think?", "no crees"),
        ("did you", "didja", "{{c1::Did you}} go?", "fuiste"),
        ("what do you", "whaddya", "{{c1::What do you}} mean?", "qué quieres decir / qué"),
        ("out of town", "outta town", "He is {{c1::out of town}}.", "fuera de la ciudad"),
        ("a lot of", "alotta", "That is {{c1::a lot of}} work.", "mucho"),
        ("out of control", "outta control", "It got {{c1::out of control}}.", "fuera de control")
    ],
    11: [ # Dark L & L-Vocalization
        ("milk", "miwk", "Do you want some {{c1::milk}}?", "leche"),
        ("feel", "feew", "I don't {{c1::feel}} well.", "sentir"),
        ("bottle", "baa-dou", "Pass the water {{c1::bottle}}.", "botella"),
        ("help", "hewp", "Can you {{c1::help}} me?", "ayuda"),
        ("well", "wew", "He is doing {{c1::well}}.", "bien"),
        ("bell", "bew", "Ring the {{c1::bell}}.", "campana"),
        ("hill", "hiw", "We walked up the {{c1::hill}}.", "colina"),
        ("pill", "piw", "Take this {{c1::pill}}.", "pastilla"),
        ("kill", "kiw", "Don't {{c1::kill}} the insect.", "matar"),
        ("cool", "coow", "That is a {{c1::cool}} car.", "genial / fresco"),
        ("fool", "foow", "Don't be a {{c1::fool}}.", "tonto"),
        ("tool", "toow", "This is a useful {{c1::tool}}.", "herramienta"),
        ("rule", "ruew", "Follow the {{c1::rule}}.", "regla"),
        ("school", "schoow", "He is at {{c1::school}}.", "escuela"),
        ("pool", "poow", "Let's swim in the {{c1::pool}}.", "piscina"),
        ("doll", "dow", "She has a nice {{c1::doll}}.", "muñeca"),
        ("ball", "baww", "Throw the {{c1::ball}}.", "pelota"),
        ("call", "caww", "Give me a {{c1::call}}.", "llamada"),
        ("fall", "faww", "Be careful not to {{c1::fall}}.", "caer"),
        ("wall", "waww", "Hang it on the {{c1::wall}}.", "pared"),
        ("tall", "taww", "He is very {{c1::tall}}.", "alto"),
        ("hall", "haww", "Walk down the {{c1::hall}}.", "pasillo"),
        ("small", "smaww", "It's a {{c1::small}} world.", "pequeño"),
        ("mall", "maww", "We went to the {{c1::mall}}.", "centro comercial"),
        ("gold", "gowd", "She wore a {{c1::gold}} ring.", "oro"),
        ("cold", "cowd", "The water is {{c1::cold}}.", "frío"),
        ("old", "owd", "This is an {{c1::old}} house.", "viejo"),
        ("bold", "bowd", "Be {{c1::bold}} and brave.", "audaz"),
        ("fold", "fowd", "Please {{c1::fold}} the laundry.", "doblar"),
        ("sold", "sowd", "We {{c1::sold}} our car.", "vendido")
    ],
    12: [ # Intrusive Glides
        ("go out", "go-w-out", "Let's {{c1::go out}} tonight.", "salir"),
        ("do it", "do-w-it", "Just {{c1::do it}} now.", "hazlo"),
        ("see it", "see-y-it", "I want to {{c1::see it}}.", "verlo"),
        ("I am", "I-y-am", "{{c1::I am}} ready.", "yo soy / estoy"),
        ("go in", "go-w-in", "Please {{c1::go in}} first.", "entrar"),
        ("show off", "show-w-off", "Don't {{c1::show off}}.", "presumir"),
        ("slow and", "slow-w-and", "Go {{c1::slow and}} steady.", "lento y"),
        ("know about", "know-w-about", "What do you {{c1::know about}} it?", "saber sobre"),
        ("how about", "how-w-about", "{{c1::How about}} dinner?", "qué tal"),
        ("now I", "now-w-I", "{{c1::Now I}} understand.", "ahora yo"),
        ("allow it", "allow-w-it", "I can't {{c1::allow it}}.", "permitirlo"),
        ("free agent", "free-y-agent", "He is a {{c1::free agent}}.", "agente libre"),
        ("be aware", "be-y-aware", "Please {{c1::be aware}} of the risk.", "ser consciente"),
        ("three of", "three-y-of", "I need {{c1::three of}} them.", "tres de"),
        ("say it", "say-y-it", "Don't {{c1::say it}}.", "decirlo"),
        ("pay off", "pay-y-off", "It will {{c1::pay off}} eventually.", "valer la pena / pagar todo"),
        ("play it", "play-y-it", "Let's {{c1::play it}} again.", "tocarlo / jugarlo"),
        ("way out", "way-y-out", "Where is the {{c1::way out}}?", "salida"),
        ("try it", "try-y-it", "Go ahead and {{c1::try it}}.", "pruébalo"),
        ("by all", "by-y-all", "{{c1::By all}} means, go ahead.", "por todos"),
        ("my opinion", "my-y-opinion", "In {{c1::my opinion}}, it is good.", "mi opinión"),
        ("blue ink", "blue-w-ink", "Use {{c1::blue ink}} only.", "tinta azul"),
        ("shoe on", "shoe-w-on", "Put your {{c1::shoe on}}.", "zapato"),
        ("too often", "too-w-often", "Don't do it {{c1::too often}}.", "demasiado a menudo"),
        ("who is", "who-w-is", "{{c1::Who is}} there?", "quién es"),
        ("you are", "you-w-are", "{{c1::You are}} late.", "tú eres / estás"),
        ("grey area", "grey-y-area", "It's a {{c1::grey area}}.", "zona gris"),
        ("say ok", "say-y-ok", "Just {{c1::say ok}}.", "di que sí"),
        ("annoy us", "annoy-y-us", "Don't let them {{c1::annoy us}}.", "molestarnos"),
        ("boy is", "boy-y-is", "The {{c1::boy is}} tall.", "el chico es")
    ],
    13: [ # Unreleased Stops
        ("stop it", "stop-it", "Please {{c1::stop it}}.", "para"),
        ("hot dog", "hah-dog", "I bought a {{c1::hot dog}}.", "perrito caliente"),
        ("cat food", "cah-food", "Buy some {{c1::cat food}}.", "comida de gato"),
        ("big deal", "bih-deal", "It's no {{c1::big deal}}.", "gran cosa"),
        ("back pack", "bah-pack", "I carried a {{c1::back pack}}.", "mochila"),
        ("black coffee", "blah-coffee", "I drink {{c1::black coffee}}.", "café solo"),
        ("that day", "tha-day", "I remember {{c1::that day}}.", "ese día"),
        ("good morning", "guh-morning", "{{c1::Good morning}}, everyone.", "buenos días"),
        ("big picture", "bih-picture", "Look at the {{c1::big picture}}.", "panorama general"),
        ("grab that", "grah-that", "Can you {{c1::grab that}}?", "tomar eso"),
        ("bad dog", "bah-dog", "He is a {{c1::bad dog}}.", "perro malo"),
        ("sub titles", "suh-titles", "Turn on the {{c1::sub titles}}.", "subtítulos"),
        ("club house", "cluh-house", "They met at the {{c1::club house}}.", "casa club"),
        ("tub full", "tuh-full", "The {{c1::tub full}} of water was warm.", "bañera llena"),
        ("web page", "weh-page", "Visit our {{c1::web page}}.", "página web"),
        ("rib cage", "rih-cage", "He broke his {{c1::rib cage}}.", "caja torácica"),
        ("bob cat", "boh-cat", "We saw a {{c1::bob cat}}.", "lince rojo"),
        ("cup cake", "cuh-cake", "Would you like a {{c1::cup cake}}?", "magdalena / cupcake"),
        ("map reading", "mah-reading", "He is good at {{c1::map reading}}.", "lectura de mapas"),
        ("hip joint", "hih-joint", "He hurt his {{c1::hip joint}}.", "articulación de cadera"),
        ("cheap car", "cheh-car", "I bought a {{c1::cheap car}}.", "coche barato"),
        ("deep breath", "deh-breath", "Take a {{c1::deep breath}}.", "respiración profunda"),
        ("keep trying", "keh-trying", "Just {{c1::keep trying}}.", "sigue intentándolo"),
        ("sharp turn", "shah-turn", "Make a {{c1::sharp turn}}.", "giro brusco"),
        ("red car", "reh-car", "He drives a {{c1::red car}}.", "coche rojo"),
        ("sad film", "sah-film", "It was a {{c1::sad film}}.", "película triste"),
        ("mad man", "mah-man", "He is a {{c1::mad man}}.", "hombre loco"),
        ("had done", "hah-done", "I {{c1::had done}} it.", "había hecho"),
        ("did that", "dih-that", "Who {{c1::did that}}?", "hizo eso"),
        ("wet paint", "weh-paint", "Watch out for the {{c1::wet paint}}.", "pintura fresca")
    ],
    14: [ # Stress-Timed Rhythm
        ("cats chase mice", "CATS CHASE MICE", "{{c1::Cats chase mice}}.", "Los gatos persiguen ratones"),
        ("dogs bark loud", "DOGS BARK LOUD", "{{c1::Dogs bark loud}}.", "Los perros ladran fuerte"),
        ("birds sing sweet", "BIRDS SING SWEET", "{{c1::Birds sing sweet}}.", "Los pájaros cantan dulce"),
        ("fish swim fast", "FISH SWIM FAST", "{{c1::Fish swim fast}}.", "Los peces nadan rápido"),
        ("kids play outside", "KIDS PLAY OUTSIDE", "{{c1::Kids play outside}}.", "Los niños juegan afuera"),
        ("cars drive quick", "CARS DRIVE QUICK", "{{c1::Cars drive quick}}.", "Los coches conducen rápido"),
        ("planes fly high", "PLANES FLY HIGH", "{{c1::Planes fly high}}.", "Los aviones vuelan alto"),
        ("clocks tick slow", "CLOCKS TICK SLOW", "{{c1::Clocks tick slow}}.", "Los relojes marcan lento"),
        ("winds blow hard", "WINDS BLOW HARD", "{{c1::Winds blow hard}}.", "Los vientos soplan fuerte"),
        ("rains fall down", "RAINS FALL DOWN", "{{c1::Rains fall down}}.", "Las lluvias caen"),
        ("snows melt fast", "SNOWS MELT FAST", "{{c1::Snows melt fast}}.", "Las nieves se derriten rápido"),
        ("stars shine bright", "STARS SHINE BRIGHT", "{{c1::Stars shine bright}}.", "Las estrellas brillan fuerte"),
        ("fires burn hot", "FIRES BURN HOT", "{{c1::Fires burn hot}}.", "Los fuegos queman caliente"),
        ("ice feels cold", "ICE FEELS COLD", "{{c1::Ice feels cold}}.", "El hielo se siente frío"),
        ("time flies past", "TIME FLIES PAST", "{{c1::Time flies past}}.", "El tiempo vuela rápido"),
        ("work gets done", "WORK GETS DONE", "{{c1::Work gets done}}.", "El trabajo se hace"),
        ("life goes on", "LIFE GOES ON", "{{c1::Life goes on}}.", "La vida continúa"),
        ("love beats hate", "LOVE BEATS HATE", "{{c1::Love beats hate}}.", "El amor vence al odio"),
        ("truth wins out", "TRUTH WINS OUT", "{{c1::Truth wins out}}.", "La verdad triunfa"),
        ("hope stays alive", "HOPE STAYS ALIVE", "{{c1::Hope stays alive}}.", "La esperanza sigue viva"),
        ("dreams come true", "DREAMS COME TRUE", "{{c1::Dreams come true}}.", "Los sueños se hacen realidad"),
        ("words carry weight", "WORDS CARRY WEIGHT", "{{c1::Words carry weight}}.", "Las palabras tienen peso"),
        ("acts speak loud", "ACTS SPEAK LOUD", "{{c1::Acts speak loud}}.", "Los actos hablan fuerte"),
        ("art lives long", "ART LIVES LONG", "{{c1::Art lives long}}.", "El art vive largo tiempo"),
        ("books teach well", "BOOKS TEACH WELL", "{{c1::Books teach well}}.", "Los libros enseñan bien"),
        ("news spreads fast", "NEWS SPREADS FAST", "{{c1::News spreads fast}}.", "Las noticias corren rápido"),
        ("prices rise high", "PRICES RISE HIGH", "{{c1::Prices rise high}}.", "Los precios suben alto"),
        ("sales fall off", "SALES FALL OFF", "{{c1::Sales fall off}}.", "Las ventas caen"),
        ("stocks go down", "STOCKS GO DOWN", "{{c1::Stocks go down}}.", "Las acciones bajan"),
        ("funds run dry", "FUNDS RUN DRY", "{{c1::Funds run dry}}.", "Los fondos se agotan")
    ],
    15: [ # Flap D
        ("ladder", "la-der", "He climbed the wooden {{c1::ladder}}.", "escalera"),
        ("riding", "ri-ding", "She was {{c1::riding}} a horse.", "montando"),
        ("body", "bo-dy", "Keep your {{c1::body}} active.", "cuerpo"),
        ("medal", "me-dal", "He won a gold {{c1::medal}}.", "medalla"),
        ("muddy", "mu-dy", "His boots were {{c1::muddy}}.", "embarrado"),
        ("padding", "pa-ding", "The jacket has extra {{c1::padding}}.", "relleno"),
        ("heading", "hea-ding", "Where are you {{c1::heading}}?", "dirigiéndose"),
        ("loading", "loa-ding", "The page is still {{c1::loading}}.", "cargando"),
        ("made an offer", "ma-dan-offer", "They {{c1::made an offer}} on the house.", "hicieron una oferta"),
        ("hide it", "hi-dit", "Where did you {{c1::hide it}}?", "esconderlo"),
        ("she'd ask", "shee-dask", "I knew {{c1::she'd ask}} that.", "ella preguntaría"),
        ("middle", "mi-doul", "It's in the {{c1::middle}}.", "medio"),
        ("cradle", "cra-doul", "The baby slept in the {{c1::cradle}}.", "cuna"),
        ("saddle", "sa-doul", "Put the {{c1::saddle}} on the horse.", "silla de montar"),
        ("puddle", "pu-doul", "He stepped in a water {{c1::puddle}}.", "charco"),
        ("riddle", "ri-doul", "Can you solve this {{c1::riddle}}?", "acertijo"),
        ("needle", "nee-doul", "I need a thread and {{c1::needle}}.", "aguja"),
        ("noodle", "noo-doul", "She ate a hot {{c1::noodle}} soup.", "fideo"),
        ("candle", "can-doul", "Light the {{c1::candle}}.", "vela"),
        ("handle", "han-doul", "Turn the door {{c1::handle}}.", "manija / asa"),
        ("bundle", "bun-doul", "We tied it in a {{c1::bundle}}.", "paquete / manojo"),
        ("sidewalk", "si-dewalk", "Walk on the {{c1::sidewalk}}.", "acera"),
        ("wedding", "we-ding", "Are you going to the {{c1::wedding}}?", "boda"),
        ("bidding", "bi-ding", "The {{c1::bidding}} war started.", "licitación / subasta"),
        ("spider", "spi-der", "I saw a big {{c1::spider}}.", "araña"),
        ("rider", "ri-der", "He is a skilled {{c1::rider}}.", "jinete / conductor"),
        ("slider", "sli-der", "Order a mini {{c1::slider}}.", "mini hamburguesa"),
        ("glider", "gli-der", "The {{c1::glider}} flew smoothly.", "planeador"),
        ("folder", "fol-der", "Put the files in the {{c1::folder}}.", "carpeta"),
        ("builder", "buil-der", "He is a home {{c1::builder}}.", "constructor")
    ],
    16: [ # Pre-Glottalization
        ("napkin", "na'p-kin", "Use a {{c1::napkin}} to clean up.", "servilleta"),
        ("actor", "a'k-tor", "He is a famous Hollywood {{c1::actor}}.", "actor"),
        ("backward", "ba'k-ward", "He took a step {{c1::backward}}.", "hacia atrás"),
        ("apt", "a'pt", "That was an {{c1::apt}} description.", "apropiado"),
        ("captain", "ca'p-tain", "The {{c1::captain}} steered the ship.", "capitán"),
        ("doctor", "do'k-tor", "You should see a {{c1::doctor}}.", "doctor"),
        ("sector", "se'k-tor", "He works in the private {{c1::sector}}.", "sector"),
        ("aspect", "as-pe'ct", "This is an important {{c1::aspect}}.", "aspecto"),
        ("football", "foo't-ball", "We played {{c1::football}} yesterday.", "fútbol"),
        ("catnap", "ca't-nap", "I need a quick {{c1::catnap}}.", "siesta corta"),
        ("outpost", "ou't-post", "They set up an {{c1::outpost}}.", "avanzada / puesto"),
        ("nightclub", "nigh't-club", "We went to a {{c1::nightclub}}.", "discoteca"),
        ("notebook", "no'te-book", "Write it in your {{c1::notebook}}.", "cuaderno"),
        ("hatbox", "ha't-box", "She kept it in a {{c1::hatbox}}.", "caja de sombreros"),
        ("meatball", "mea't-ball", "Add a {{c1::meatball}} to the pasta.", "albóndiga"),
        ("nutshell", "nu't-shell", "Explain it in a {{c1::nutshell}}.", "pocas palabras"),
        ("witness", "wi't-ness", "He was a key {{c1::witness}}.", "testigo"),
        ("fitness", "fi't-ness", "Physical {{c1::fitness}} is vital.", "aptitud física"),
        ("sweetheart", "swee't-heart", "She is a real {{c1::sweetheart}}.", "cariño"),
        ("outfit", "ou't-fit", "I love your {{c1::outfit}}.", "atuendo"),
        ("hotspot", "ho't-spot", "Connect to the Wi-Fi {{c1::hotspot}}.", "punto de acceso"),
        ("upset", "u'p-set", "Don't get {{c1::upset}}.", "molesto"),
        ("network", "ne't-work", "The computer {{c1::network}} is down.", "red"),
        ("artistic", "ar't-istic", "She has an {{c1::artistic}} talent.", "artístico"),
        ("partnership", "par't-nership", "We formed a new {{c1::partnership}}.", "asociación"),
        ("hardship", "har'd-ship", "They faced financial {{c1::hardship}}.", "dificultades"),
        ("friendship", "frien'd-ship", "I value our {{c1::friendship}}.", "amistad"),
        ("courtship", "cour't-ship", "It was a long {{c1::courtship}}.", "cortejo"),
        ("citizenship", "citi'zen-ship", "He applied for {{c1::citizenship}}.", "ciudadanía"),
        ("membership", "mem'ber-ship", "Renew your library {{c1::membership}}.", "membresía")
    ],
    17: [ # Advanced Auxiliary Chunks
        ("what did you do", "whadja do", "{{c1::What did you do}} last weekend?", "qué hiciste"),
        ("did you ever", "jever", "{{c1::Did you ever}} climb a mountain?", "alguna vez has"),
        ("would have been", "woulda bin", "That {{c1::would have been}} great.", "habría sido"),
        ("what do you mean", "whadaya mean", "{{c1::What do you mean}} by that?", "qué quieres decir"),
        ("do you know what I mean", "ya know whad-I mean", "{{c1::Do you know what I mean}}?", "sabes a lo que me refiero"),
        ("I don't know what you're", "I dunno whacha", "{{c1::I don't know what you're}} talking about.", "no sé de qué estás"),
        ("what do you want", "whaddya want", "{{c1::What do you want}} to eat?", "qué quieres"),
        ("where did you go", "wheredja go", "{{c1::Where did you go}}?", "adónde fuiste"),
        ("how did you get", "howdja get", "{{c1::How did you get}} here?", "cómo llegaste"),
        ("why did you say", "whydja say", "{{c1::Why did you say}} that?", "por qué dijiste"),
        ("who did you meet", "whoodja meet", "{{c1::Who did you meet}}?", "con quién te reuniste"),
        ("could have been", "coulda bin", "It {{c1::could have been}} worse.", "podría haber sido"),
        ("should have done", "shoulda done", "You {{c1::should have done}} it.", "deberías haber hecho"),
        ("must have gone", "musta gone", "He {{c1::must have gone}} home.", "debe haberse ido"),
        ("what are you going to", "whatcha gonna", "{{c1::What are you going to}} do?", "qué vas a"),
        ("when did you arrive", "whendja arrive", "{{c1::When did you arrive}}?", "cuándo llegaste"),
        ("do you want to", "d'ya wanna", "{{c1::Do you want to}} grab a coffee?", "quieres"),
        ("what did you say", "whadja say", "{{c1::What did you say}}?", "qué dijiste"),
        ("did you like it", "dija like-it", "{{c1::Did you like it}}?", "te gustó"),
        ("would you have", "wouldja-av", "{{c1::Would you have}} gone?", "habrías ido"),
        ("could you have", "couldja-av", "{{c1::Could you have}} done it?", "podrías haberlo hecho"),
        ("should you have", "shouldja-av", "{{c1::Should you have}} told me?", "deberías haberme dicho"),
        ("did you see him", "dija see-im", "{{c1::Did you see him}}?", "lo viste"),
        ("what did you get", "whadja get", "{{c1::What did you get}}?", "qué conseguiste"),
        ("did you think", "dija think", "What {{c1::did you think}}?", "qué pensaste"),
        ("do you have to", "d'ya hafta", "{{c1::Do you have to}} go?", "tienes que"),
        ("does he want to", "d'zy wanna", "{{c1::Does he want to}} come?", "él quiere"),
        ("what is he doing", "whadsy doing", "{{c1::What is he doing}}?", "qué está haciendo él"),
        ("where is he going", "wheresy going", "{{c1::Where is he going}}?", "adónde va él"),
        ("why did you go", "whydja go", "{{c1::Why did you go}} there?", "por qué fuiste")
    ],
    18: [ # Syllabic Consonants
        ("sudden", "sudd-n", "There was a {{c1::sudden}} change.", "repentino"),
        ("rhythm", "rhyth-m", "I like the {{c1::rhythm}} of the music.", "ritmo"),
        ("little", "litt-l", "Just a {{c1::little}} bit, please.", "pequeño / poco"),
        ("bottle", "bott-l", "Pass the water {{c1::bottle}}.", "botella"),
        ("button", "butt-n", "Press the red {{c1::button}}.", "botón"),
        ("garden", "gard-n", "We walked in the {{c1::garden}}.", "jardín"),
        ("prison", "priz-n", "He was sent to {{c1::prison}}.", "prisión"),
        ("national", "nash-nl", "Today is a {{c1::national}} holiday.", "nacional"),
        ("cotton", "cott-n", "This shirt is 100% {{c1::cotton}}.", "algodón"),
        ("kitten", "kitt-n", "The {{c1::kitten}} is sleeping.", "gatito"),
        ("middle", "midd-l", "He is in the {{c1::middle}} of a meeting.", "mitad"),
        ("table", "tayb-l", "Leave it on the {{c1::table}}.", "mesa"),
        ("apple", "app-l", "She ate a red {{c1::apple}}.", "manzana"),
        ("simple", "simpl", "It's a very {{c1::simple}} solution.", "simple"),
        ("channel", "chann-l", "Change the TV {{c1::channel}}.", "canal"),
        ("tunnel", "tunn-l", "The train went through a {{c1::tunnel}}.", "túnel"),
        ("symbol", "symb-l", "What does this {{c1::symbol}} mean?", "símbolo"),
        ("rhythm", "rhyth-m", "The heartbeat has a steady {{c1::rhythm}}.", "ritmo"),
        ("blossom", "bloss-m", "The cherry trees are in {{c1::blossom}}.", "flor / florecer"),
        ("bottom", "bott-m", "It is at the {{c1::bottom}} of the page.", "fondo / parte inferior"),
        ("custom", "cust-m", "It is an old local {{c1::custom}}.", "costumbre"),
        ("system", "syst-m", "The operating {{c1::system}} is upgrading.", "sistema"),
        ("victim", "vict-m", "He was a {{c1::victim}} of the scam.", "víctima"),
        ("seldom", "seld-m", "We {{c1::seldom}} see each other.", "rara vez"),
        ("wisdom", "wisd-m", "He shared his words of {{c1::wisdom}}.", "sabiduría"),
        ("freedom", "freed-m", "We value our {{c1::freedom}}.", "libertad"),
        ("kingdom", "kingd-m", "Welcome to the United {{c1::Kingdom}}.", "reino"),
        ("handsome", "hands-m", "He is a {{c1::handsome}} young man.", "guapo"),
        ("awesome", "awes-m", "That was an {{c1::awesome}} show.", "increíble"),
        ("bother", "both-r", "Don't {{c1::bother}} me.", "molestar")
    ]
}
